---
- name: ensure os is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 300

- name: install packages
  apt: pkg={{ item }} state=present
  with_items:
    - bash-completion
    - curl
    - exiftool
    - fuse
    - glances
    - git
    - htop
    - iftop
    - iotop
    - jq
    - lynx
    - mc
    - ncdu
    - nmap
    - openssh-server
    - python
    - reptyr
    - screen
    - smartmontools
    - sudo
    - tmux
    - tree
    - wget
    - xfsprogs
    - youtube-dl
  tags:
    - packages

- name: create /mnt points
  file:
    dest: "/mnt/{{ item }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  with_items: "{{ mntpoints }}"

- name: mount disks
  mount:
    name: "{{ item.name }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fs }}"
    # change to 'mounted' to auto mount
    state: present
  with_items:
    - { name: /mnt/parity1, src: /dev/disk/by-id/ata-Hitachi_HUA722020ALA331_BFHVNX3F-part1, fs: xfs}
    - { name: /mnt/disk1, src: /dev/disk/by-id/ata-Hitachi_HUA722020ALA331_B8KZN16W-part1, fs: xfs}
    - { name: /mnt/disk2, src: /dev/disk/by-id/ata-Hitachi_HUA722020ALA331_B9GUGPWF-part1, fs: xfs}
    - { name: /mnt/disk3, src: /dev/disk/by-id/ata-Hitachi_HUA722020ALA331_BEH20BEW-part1, fs: xfs}
    - { name: /mnt/disk4, src: /dev/disk/by-id/ata-ST3500630AS_5QG06YKF-part1, fs: xfs}
    - { name: /mnt/disk5, src: /dev/disk/by-id/ata-ST3500630AS_9QG22507-part1, fs: xfs}
    - { name: /mnt/disk6, src: /dev/disk/by-id/ata-ST3320613AS_9SZ69NGV-part1, fs: xfs}

- name: mount mergerfs array
  mount:
    name: /mnt/storage
    src: /mnt/disk*
    opts: direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs
    fstype: fuse.mergerfs
    # change to 'mounted' to auto mount
    state: present
